/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/model02.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="OverallParent" position={[0.06, 4.04, 0.35]} scale={0.25}>
          <mesh name="Headphones" geometry={nodes.Headphones.geometry} material={materials.M_Headphone} />
          <mesh name="Notebook" geometry={nodes.Notebook.geometry} material={materials.M_Notebook} />
          <mesh name="Rocket003" geometry={nodes.Rocket003.geometry} material={materials.M_Rocket} />
          <mesh name="Roundcube001" geometry={nodes.Roundcube001.geometry} material={materials.M_Roundcube} />
          <mesh name="Table" geometry={nodes.Table.geometry} material={materials.M_Table} />
          <mesh name="VR_Headset" geometry={nodes.VR_Headset.geometry} material={materials.M_Headset} />
          <mesh name="Zeppelin" geometry={nodes.Zeppelin.geometry} material={materials.M_Zeppelin} />
        </group>
        <group name="Camera001" position={[-10.72, -5.98, 2.3]} rotation={[1.36, 0.56, 1.95]}>
          <PerspectiveCamera name="Camera_Orientation" makeDefault={false} far={100} near={0.1} fov={22.9} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model02.glb')
