/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Test01.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="ModelList">
          <mesh name="Cone" geometry={nodes.Cone.geometry} material={materials['Material.001']} />
          <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials['Material.002']} />
          <mesh name="Sphere" geometry={nodes.Sphere.geometry} material={materials['Material.003']} />
          <mesh name="Suzanne" geometry={nodes.Suzanne.geometry} material={materials['Material.004']} />
        </group>
        <group name="Camera">
          <PerspectiveCamera name="CameraMain" makeDefault={false} far={1000} near={0.1} fov={22.9} rotation={[2.66, 1.5, -2.64]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Test01.glb')
